### ISSUE TITLE
Explore possibility of making a remote interface

### ISSUE THREAD

**Issue by 153957** [HiSPARC/correlation#9]
Not 'all' high school computers have Python installed, and some teachers/students are not allowed to install it.
We might be able to provide a service to do some python stuff on our server with which the students can interact via a website.

**Comment by 153957** [comment]
Perhaps this can be done by making HTML and Javascript pages, which use the Publicdb API (#8)

**Comment by davidfokkema** [comment]
I'm all for building a good API which can be used to obtain data or reconstruct events, or ...?

**Comment by 153957** [comment]
In this case, for retrieving data, which javascript could then plot and analyse.

**Comment by 153957** [comment]
This is mostly implemented in data_retrieval.html in [jSparc](https://github.com/HiSPARC/jsparc)
